### ISSUE TITLE
How to call the function

### ISSUE THREAD

**Issue by abdokouta** [BenAOlson/gatsby-plugin-firebase-messaging#5]
so i have read your note: the Firebase messaging service worker won’t be registered in your app until messaging().getToken() is called. so how can i call the messaging().getToken() function? i'm trying tp build custom push notification prompt and i have achieved the scope with pure reactjs but i'm getting issue with the build and also i saw ur plugin and u are handling service worker registration so i need a little help over here, please  

`
import { connect } from "react-redux"
import React, { Component } from "react"
import firebase from 'firebase/app';
import "firebase/messaging"
import config from "~config"

const firebaseApp = firebase.initializeApp(config.google.firebase.credentials)

const messaging = firebaseApp.messaging()

class PushNotificationPromote extends Component {
  constructor() {
    super()
    this.state = {
      status: "info",
      message: "Token will be displayed here..!",
      title: "Notifications will appear here..!",
      msgCount: "Notification Count: 0",
    }
    this.handleClick = this.handleClick.bind(this)
  }

  handleClick() {
    console.log(messaging)
    messaging
      .requestPermission()
      .then(() => {
        console.log("Notification permission granted.")
        messaging
          .getToken()
          .then(currentToken => {
            if (currentToken) {
              console.log("Token generated is ", currentToken)
              this.setState(...this.state, {
                status: "success",
                message: currentToken,
              })
              // sendTokenToServer(currentToken);
              // updateUIForPushEnabled(currentToken);
            } else {
              // Show permission request.
              console.log(
                "No Instance ID token available. Request permission to generate one."
              )
              this.setState(...this.state, {
                status: "error",
                message:
                  "No Instance ID token available. Request permission to generate one.",
              })

              // Show permission UI.
              // updateUIForPushPermissionRequired();
              // setTokenSentToServer(false);
            }
          })
          .catch(err => {
            console.log("An error occurred while retrieving token. ", err)
            this.setState(...this.state, {
              status: "error",
              message: "An error occurred while retrieving token.",
            })

            // showToken('Error retrieving Instance ID token. ', err);
            // setTokenSentToServer(false);
          })
      })
      .catch(err => {
        console.log("Unable to get permission to notify.", err)
      })
  }

  render() {
    return (
      <div>
        <div>
          <button onClick={this.handleClick}> Generate Token </button>
        </div>
        <div>
          <p>{this.state.message}</p>
        </div>
        <div>
          <p>{this.state.msgCount}</p>
        </div>
      </div>
    )
  }
}

PushNotificationPromote.propsType = {}

const mapStateToProps = state => ({})

const mapDispatchToProps = dispatch => ({})

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(PushNotificationPromote)

`

**Comment by BenAOlson** [comment]
I'm a little confused, because it looks like your code is calling `messaging.getToken()` in your `handleClick` method, which is exactly what you'd need to do. Is it not working?

Sorry for the slow reply--I didn't realize until today that I wasn't getting email notifications (whoops!)
