### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by dhanushp** [BenAOlson/gatsby-plugin-firebase-messaging#6]
Hey there, I'm sorry to disturb. I'm new to firebase and I'm finding hard time setting up cloud messaging to my PWA app.

**note: the Firebase messaging service worker won't be registered in your app until messaging().getToken() is called.**

Can you please tell me what this means? I have been reading some blogs on freecodecamp have some basic understanding. it will be really helpful if you could help me in setting up cloud messaging.
Thank you.

**Comment by dhanushp** [comment]
@BenAOlson

**Comment by BenAOlson** [comment]
I just put that note in the readme to let people know that the service worker won't actually be registered until you get a registration token from your user. You'll need a registration token to identify the user and send them notifications.

https://firebase.google.com/docs/cloud-messaging/js/client

**Comment by dhanushp** [comment]
It would really helpful if you could write a blog on how to setup and use Firebase Cloud Messaging in Gatsbyjs 😃 I have already setup PWA for my website, just not able to get around FCM. I searched all over internet and not able to find any single blog related to that 😞 
Thank you.
