### ISSUE TITLE
HELP - How to install?

### ISSUE THREAD

**Issue by brendoncarvalho** [BenAOlson/gatsby-plugin-firebase-messaging#7]
Hi, sorry for the question, maybe even an idiot.

After adding the plugin to the "gatsby-config.js" file, what do I have to do to work?

note: the Firebase messaging service worker won’t be registered in your app until **messaging().getToken()** is called.

Where do I add **messaging().getToken()**?

Tks

**Comment by BenAOlson** [comment]
So all this plugin does is take care of the boilerplate for creating a serviceworker file, basically.

`messaging().getToken()` is something you'll call in your Gatsby code to retrieve a Firebase messaging token that you can use to send messages to your users.

There is a really nice guide at the [firebase docs](https://firebase.google.com/docs/cloud-messaging/js/client) that can help get you started.
