### ISSUE TITLE
Token is not generated.

### ISSUE THREAD

**Issue by ashishch-98** [BenAOlson/gatsby-plugin-firebase-messaging#8]
I have installed the plugin, but I am not able to send notifications to PWA, neither on the localhost nor to the live website. I think I did not write the code for FCM like it is done for react apps. I have gatsby offline plugin and then added keys to the gatsby-plugin-firebase-messaging plugin as defined in the readme. How do I register getToken()? Do I need to create a js file and then add it to the config? Can you please clarify how to call the function?

**note: the Firebase messaging service worker won’t be registered in your app until messaging().getToken() is called.**

**Comment by BenAOlson** [comment]
I should remove that line from the readme.

You will need a token for each client to send them a message. firebase.messaging().getToken() is the method from the firebase SDK that gets a token for that client. For example, if you wanted to send a test mesaage from the fire are dashboard, you would need to enter a token to send it.

When or where you call that method is entirely up to you. It should probably be in response to a user input (like a button to subscribe to a notification topic or something). That's when you get the token for that client, and do whatever you want to do with it related to how you will store and use those tokens to send push notifications. For example, maybe you subscribe that token to a topic.

For more information, see the FCM documentation.

**Comment by ashishch-98** [comment]
Thank you for your explanation. I figured out how to achieve it and works great in development mode, but on running `gatsby build` new errors start popping up. The error message is:
```
See our docs page for more info on this error: https://gatsby.dev/debug-html


  24 | 
  25 |       // Retrieve Firebase Messaging object.
> 26 |       const messaging = firebase.messaging();
     |                                  ^
  27 | 
  28 | 
  29 | 


  WebpackError: TypeError: gatsby_plugin_firebase_messaging__WEBPACK_IMPORTED_MODULE_1___default.a.messaging is 
  not a function

  - PushNotifications.js:26 
    src/components/PushNotifications.js:26:34
```

I think there is something to do with imports. In my component, I  have imported `import firebase from 'gatsby-plugin-firebase-messaging'` and in development mode, it works as it should but on build it throws the above error. 

I also tried to use the npm package of [firebase](https://www.npmjs.com/package/firebase) with the defined imports followed by initializing the firebaseConfig.
```
import firebase from 'firebase'
import 'firebase/messaging'
```
This method also worked in development but on build gave other error messages. You can check the issue [here.](https://github.com/gatsbyjs/gatsby/discussions/27741)

Can you please guide on the correct imports in component?

**Comment by BenAOlson** [comment]
Definitely, this plugin doesn't export anything, and so importing from it won't work.

I'm very sorry that I've been a bit busy and can't help further, but I think you may be running into some general conceptual problems related to Gatsby and Firebase. Figuring out the messaging part maybe should come after figuring out those pieces?

One thing is understanding how Gatsby builds projects. The build step runs entirely in a nodejs environment, and so will behave differently than in the browser. Your firebase code should only run in the client, and not in the build environment. This is a general concept related to Gatsby.

If you haven't built any projects on your own using Firebase and React yet, and you have the time, I would definitely recommend trying to build something simple with regular React and Firebase first, as Gatsby is just React but with more complications. There are probably lots of tutorials to help with that! It will also be easier to figure out the messaging portion of things there.

Sorry I can't help more right now. Godspeed!
