### ISSUE TITLE
The plugin is incompatible with the current gatsby-plugin-firebase

### ISSUE THREAD

**Issue by idosius** [BenAOlson/gatsby-plugin-firebase-messaging#9]
I've installed `gatsby-plugin-firebase` which uses Firebase version 8.0.1. Then I installed `gatsby-plugin-firebase-messaging` which uses Firebase version 7.9.3. Unfortunately, this caused bugs since these versions are not aligned.

To fix this issue, `gatsby-plugin-firebase-messaging` should have an option which Firebase version to use and import the according scripts. By default, it should import the latest Firebase version.

**Comment by BenAOlson** [comment]
~I'm confused, because this plugin doesn't use firebase at all~

Wait, nevermind. Good call. I'll fix this later.

**Comment by BenAOlson** [comment]
I've gone ahead and just updated the script to 8.0.1 for the short term before implementing a more long-term fix.

**Comment by BenAOlson** [comment]
Just published v1.1.0, which uses the firebase version from your package-lock.json or yarn.lock, and provides an option to specify a specific firebase version if you want.
